### ISSUE TITLE
Fatal error when trying to load P6 on PHP 5.2

### ISSUE THREAD

**Issue by redmetyellowcreative** [netrivet/prophoto-issues#1]
Hey guys! 

Just tried to install P6 and got a parse error. Here's the full message: 

Parse error: syntax error, unexpected T_STRING in /home/content/76/10123876/html/prophotostaging/wp-content/themes/prophoto6/functions.php on line 36

**Comment by brianium** [comment]
hey @redmetyellowcreative - what version of PHP are you running? This looks like you might be on version 5.2.

**Comment by redmetyellowcreative** [comment]
Yes, it shows as 5 on my host. Can I update that on my own, or would I have to go through Godaddy? I wanted to upload the file in a new design in the back end of ProPhoto Store, but there is nowhere to upload the Theme. Is this correct?

**Comment by jaredh159** [comment]
@redmetyellowcreative we think this is almost certainly due to the fact that you're probably running PHP 5.2. P6 requires 5.3 or higher.

Because you can't get into P6 to use the feedback widget, I'll shoot you an email so I can get your FTP login so I can try to make it so it displays a helpful error message instead of just throwing up. Can you check your email in about 2 minutes?

Don't put your FTP info here, this is public.

**Comment by redmetyellowcreative** [comment]
Thanks @brianium and @jaredh159!

**Comment by brianium** [comment]
:+1:
