### ISSUE TITLE
Create Phinx wpdb adapter

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#176]

**Comment by jaredh159** [comment]
Completed by https://github.com/netrivet/prophoto-classes/pull/483

**Comment by stevep** [comment]
I'm looking to do migrations in WordPress and was thinking about utilizing Phinx. Typing them both into Google landed me to this issue.

I'm guessing https://github.com/netrivet/prophoto-classes/pull/483 links to a private repository but did you have success creating a wpdb adapter? How are you using it?  Thanks!

**Comment by brianium** [comment]
@stevep we are in fact using a custom adapter. It basically funnels all migration operations through `wpdb`. That comes with a handful of tradeoffs, and our adapter could probably do more to optimize for different engines re: MyISAM and InnoDB. But, it has been really useful for pushing out database changes to our users :) - I'll check with the boss man and see if there is any issue sharing.

**Comment by stevep** [comment]
Awesome, exactly what I was looking to do, thanks for checking!

Are your migrations being run by your users via command line, or are they invisible to the user and get run automatically on plugin activation?

**Comment by brianium** [comment]
We keep the migrations invisible to the user. They are run on activation and when we push updates. We have no problem sharing the code either. Ideally we will get a repo up with our code, but at the very least I'll get a gist linked here for you to play around with. Look for something within the next couple days - just need to make some time to do this :)

**Comment by brianium** [comment]
@stevep I am going to leave several gists here with our implementation. Some of the gists have brief explanations at the bottom. We might open source a more fully fledged solution in the future, but we are going to hold off for now just because it might take some effort to make it more broadly applicable.

The two files required for the custom adapter are here:
[WpdbAdapter](https://gist.github.com/brianium/3f0857e16c4a0fbb1080c34099bf8d10)
[PdoLikeObject](https://gist.github.com/brianium/daaf5228fe30cb16b65d3fa79e5faa3d)

You may notice a little good natured snark in the `WpdbAdapter` class in the comments, but that just exists for the void methods we did not implement. Mostly the methods that would be used for `InnoDB` (transactions, foreign keys). As noted in that gist - transactions and foreign keys shouldn't be too hard to implement, but we have tailored to the lowest common denominator and stuck with `MyISAM` for our DB engine. 

If you want a code base for running migrations in an update/activation hook, you may want a custom migration manager. If so, here is the code we use for that:
[WordPressManager](https://gist.github.com/brianium/1e854980e57bad365f723b0267569a74)
[MigratorInterface](https://gist.github.com/brianium/718020b707e3f2bc339ae8fe6bc7cce7)

Having a custom manager here simplifies configuration (as you can read connection details off the WordPress DB constants), and is useful for running migrations via your own CLI apps or other services.

Let me know if you have any questions or if you make any improvements. Hope it's useful :)

**Comment by brianium** [comment]
The following was tested against this Phinx version constraint (a-la composer):
`"robmorgan/phinx": "^0.4@stable"`

**Comment by stevep** [comment]
@brianium thank you so much for taking the time to do this, I appreciate it very much. This is great work. I'm hoping to create migrations for renaming ACF fields on existing data, and maybe even extracting a library out of it.
