### ISSUE TITLE
Post separator shouldn't be displayed on the last post

### ISSUE THREAD

**Issue by meatwad5675** [netrivet/prophoto-issues#268]
https://prophoto6.zendesk.com/agent/tickets/716

**Comment by postmastersteve** [comment]
It seems that the article-footer element is what this is about? It also appears below individual pages and takes up extra space even when empty.

**Comment by lalunecreative** [comment]
The .article-footer has always been in prophoto, it's basically a wordpress box to give spacing below posts. I've always just coded it out because it's annoying though, especially since all the spacing settings are done within the theme. It would be nice to have an option somewhere to turn it off globally.

This particular ticket is about the post separator line if you have one turned on, which is showing up at the very bottom of all the posts when it shouldn't be.

**Comment by brianium** [comment]
A fix for this has been added. It should be included in the next update.
