### ISSUE TITLE
Column top-padding not working in Firefox

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#358]
Steps to reproduce:

* add a bunch of column top padding to a column
* compare chrome and firefox

**Comment by meatwad5675** [comment]
Firefox bases top/bottom %-based padding of flex container children off of the declared height of the parent.  Chrome/Webkit/IE base it off of the relative width of the parent.  Apparently Firefox is more in line with the spec, even though the behavior doesn't seem very useful:

https://bugzilla.mozilla.org/show_bug.cgi?id=958714

Solution is to add another div inside of the column so that the inner div (that gets the top/bottom padding values) isn't a child of the .row flex container any more.
