### ISSUE TITLE
Header Video

### ISSUE THREAD

**Issue by modernistudios** [netrivet/prophoto-issues#443]
When will we see a header video that takes up the whole display of webscreen?

**Comment by modernistudios** [comment]
Look at this design for reference would really love this options as a video production team. 

https://www.pelotoncycle.com/

**Comment by jaredh159** [comment]
This is already possible with a little tweaking, see our P6 design _resurrection_ here:

https://www.prophoto.com/store/resurrection/

We also have an open ticket to make this simpler and more built-in:

https://github.com/netrivet/prophoto-issues/issues/363

Go ahead and +1 that issue, I'm going to close this issue because it's a duplicate.  Thanks for your feedback!

**Comment by modernistudios** [comment]
Jared Really quick how do we do this? ive been racking my brain now for 5 weeks trying to figure this out any clues?

**Comment by creative-resort** [comment]
Have a look here, @modernistudios :
https://github.com/netrivet/prophoto-issues/issues/363

**Comment by modernistudios** [comment]
when I put my video from embeded code in my wiget layer it does not complete the look?
