### ISSUE TITLE
Design of header example

### ISSUE THREAD

**Issue by modernistudios** [netrivet/prophoto-issues#446]
i was hoping to know if as a video production company if at some point we will see the option to do this on our pro photo 6. 

https://www.pelotoncycle.com/ Check out this link to see header video example

**Comment by jaredh159** [comment]
This is already possible with a little tweaking, see our P6 design _resurrection_ here:

https://www.prophoto.com/store/resurrection/

We also have an open ticket to make this simpler and more built-in:

https://github.com/netrivet/prophoto-issues/issues/363

Go ahead and +1 that issue, I'm going to close this issue because it's a duplicate.  Thanks for your feedback!
