### ISSUE TITLE
Touch devices can swipe to see mobile menu when no hamburger

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#622]
On an iPad, for instance, when viewing at an orientation/size where the user has indicated that they don't want the mobile menu visible, the user can still swipe to see the mobile menu.  This swipe action should be disabled when the mobile menu is hidden.

**Comment by danjonlam** [comment]
+1 Jeff Ascough ticket 160254 - when mobile menu is set to display "right", pinching to zoom on images can cause mobile menu to slide open

**Comment by brianium** [comment]
Kind of feel like swipe to open is more trouble than its worth. We should consider making the hamburger just function as tap to open.

**Comment by lalunecreative** [comment]
As far as user experience goes, I don't think people KNOW you can swipe to show the menu. There's no indication that you can do it, and most people know to just tap the icon to open/close. I like the feature, but because of the update to iOS 10 which allows you to swipe left/right when you have multiple tabs open in the browser this can get glitchy anyway depending on where you first tap to swipe from, that glitchiness comes more from the phone than the iPad.

**Comment by lalunecreative** [comment]
You essentially can only swipe from the middle with that feature built into iOS10 now. I think originally me and Matt got the idea from back when Squarespace had this feature. They've since switched to an old school footer menu. If you can fix it, awesome, but I could go both ways it.

**Comment by brianium** [comment]
Awesome. That is helpful. I'm going to vote for the chopping block personally 😈  - but of course ProPhoto is a democracy.

**Comment by benjamintennant** [comment]
+1 Eddie Bojorquez ticket 162941 - wants a way to disable swipe to open mobile menu

**Comment by postmastersteve** [comment]
+1 Zoe Alcock ticket 165830

**Comment by danjonlam** [comment]
+1 Suzanne Taylor ticket 168139

**Comment by benjamintennant** [comment]
+1 Aidan Dockery ticket 170150 wants to disable swipe

**Comment by postmastersteve** [comment]
Fixed in ProPhoto 6.21.0
https://github.com/netrivet/prophoto-issues/blob/master/CHANGELOG.md#6210
